name: Generate M3U8 Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Download playlist
        run: |
          yt-dlp -j --flat-playlist "https://www.youtube.com/playlist?list=PLFBDLoOnasZuSpdq5JRcs2vd6ICccdDBX" > scripts/playlist.txt

      - name: Create M3U8 file
        run: |
          python scripts/create_m3u8.py

      - name: Commit M3U8 file
        run: |
          git config --local user.email "you@example.com"  # Replace with your email
          git config --local user.name "Your Name"          # Replace with your name
          git add scripts/playlist.m3u8
          git commit -m "Update playlist.m3u8" || echo "No changes to commit"
          git push
